'use client';
import React,{createContext,useContext,useEffect,useState,ReactNode}from'react';
import{User,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut,onAuthStateChanged,sendPasswordResetEmail}from'firebase/auth';
import{doc,setDoc,getDoc}from'firebase/firestore';
import{auth,db}from'../lib/firebase';
interface UserProfile{uid:string;displayName:string;email:string;photoURL?:string;createdAt:string}
interface AuthContextType{user:User|null;profile:UserProfile|null;loading:boolean;login:(email:string,password:string)=>Promise<void>;signup:(email:string,password:string,displayName:string)=>Promise<User>;logout:()=>Promise<void>;resetPassword:(email:string)=>Promise<void>}
const AuthContext=createContext<AuthContextType|undefined>(undefined);
export function AuthProvider({children}:{children:ReactNode}){var[user,su]=useState<User|null>(null);var[profile,sp]=useState<UserProfile|null>(null);var[loading,sl]=useState(true);useEffect(function(){var tid=setTimeout(function(){sl(false)},2500);var unsub;if(auth){try{unsub=onAuthStateChanged(auth,function(fu){clearTimeout(tid);su(fu);if(fu){getDoc(doc(db,'users',fu.uid)).then(function(pd){if(pd.exists()){sp(pd.data()as UserProfile)}else{var np:UserProfile={uid:fu.uid,displayName:fu.displayName||'',email:fu.email||'',createdAt:new Date().toISOString()};setDoc(doc(db,'users',fu.uid),np).catch(function(){});sp(np)}}).catch(function(){})}else{sp(null)}sl(false)})}catch(err){console.error('Auth error:',err);clearTimeout(tid);sl(false)}}else{clearTimeout(tid);sl(false)}return function(){clearTimeout(tid);if(unsub)unsub()}},[]);var login=async function(email,password){await signInWithEmailAndPassword(auth,email,password)};var signup=async function(email,password,displayName){var cred=await createUserWithEmailAndPassword(auth,email,password);var np:UserProfile={uid:cred.user.uid,displayName,email:cred.user.email||'',createdAt:new Date().toISOString()};await setDoc(doc(db,'users',cred.user.uid),np);return cred.user};var logout=async function(){await signOut(auth);sp(null)};var resetPassword=async function(email){await sendPasswordResetEmail(auth,email)};return React.createElement(AuthContext.Provider,{value:{user,profile,loading,login,signup,logout,resetPassword}},children)}
export function useAuth(){var ctx=useContext(AuthContext);if(!ctx)throw new Error('useAuth must be used within AuthProvider');return ctx}