
"use client";
import React from"react";import{useState,useEffect}from"react";
import{initializeApp,getApps}from"firebase/app";
import{getAuth,signOut,onAuthStateChanged}from"firebase/auth";
import{getFirestore,collection,addDoc,query,where,getDocs,orderBy,doc,getDoc,updateDoc}from"firebase/firestore";
import Sidebar from"@/components/Sidebar";
var cfg={apiKey:"AIzaSyAAORXxX6tBpfCAtkEvWD_ls_VDhZuMdro",authDomain:"code-vidya-hack-day-ps-3-6b47d.firebaseapp.com",projectId:"code-vidya-hack-day-ps-3-6b47d"};var app=getApps().length?getApps()[0]:initializeApp(cfg);var auth=getAuth(app);var db=getFirestore(app);
function analyzeText(t){var items=[];var lines=t.split(/[.\n]+/);lines.forEach(function(l){var tl=l.trim();if(!tl)return;var m=tl.match(/(\w+)\s+will\s+(.+)/i);if(!m)return;var name=m[1].trim();var task=m[2].trim();var dl="";var pr="MEDIUM";if(task.match(/tomorrow|next\s+week|by\s+/i)){dl=new Date(Date.now()+86400000).toISOString().split("T")[0];pr="HIGH"}else if(task.match(/tonight|today|asap|immediately|urgent/i)){dl=new Date().toISOString().split("T")[0];pr="HIGH"}if(task.match(/critical|important|must|backup|emergency|required/i))pr="CRITICAL";if(task.match(/please|can|could|maybe|possibly|think|might/i))return;items.push({task:task.charAt(0).toUpperCase()+task.slice(1),name:name,deadline:dl||null,priority:pr,selected:true})});var risks=[];if(t.match(/not\s+confirmed|backup\s+venue|cancelled|cancel|missing|don't\s+have/i))risks.push({title:"Unconfirmed items",description:"Some items need attention",severity:"HIGH"});if(t.match(/overloaded|busy|stressed|help/i))risks.push({title:"Workload concern",description:"Team may be overloaded",severity:"MEDIUM"});return{items:items,risks:risks}}
export default function MeetingsPage(){var[user,su]=React.useState(null);var[ck,sc]=React.useState(false);var[clubs,scl]=React.useState([]);var[cid,scid]=React.useState(null);var[club,sclub]=React.useState(null);var[meetings,sm]=React.useState([]);var[ld,sld]=React.useState(true);var[sh,ssh]=React.useState(false);var[rn,srn]=React.useState("");var[f,sf]=React.useState({title:"",date:"",transcript:""});var[analysis,sa]=React.useState(null);var[analyzing,saz]=React.useState(false);React.useEffect(function(){var un=onAuthStateChanged(auth,function(u){if(!u){window.location.href="/login";return}su(u);sc(true)});return function(){un()}},[]);React.useEffect(function(){if(ck)L()},[ck]);
async function L(){try{var q=query(collection(db,"clubMembers"),where("userId","==",user.uid),where("status","==","ACTIVE"));var sn=await getDocs(q);var mc=(await Promise.all(sn.docs.map(async function(d){var m=d.data();var c=await getDoc(doc(db,"clubs",m.clubId));if(!c.exists())return null;return{id:c.id,...c.data(),membershipRole:m.role}}))).filter(Boolean);scl(mc);if(mc.length>0){scid(mc[0].id);sclub(mc[0]);if(mc[0].membershipRole==="OWNER")srn("Owner");loadM(mc[0].id)}sld(false)}catch(e){sld(false)}}
async function loadM(id){try{var sn=await getDocs(query(collection(db,"meetings"),where("clubId","==",id),orderBy("createdAt","desc")));sm(sn.docs.map(function(d){return{id:d.id,...d.data()}}))}catch(e){}}
async function cr(){try{await addDoc(collection(db,"meetings"),{...f,clubId:cid,participants:[],createdBy:user.uid,createdAt:new Date().toISOString(),aiProcessed:false});ssh(false);sf({title:"",date:"",transcript:""});if(cid)loadM(cid)}catch(e){}}

async function approveItems(){if(!analysis||!cid)return;try{for(var i=0;i<analysis.items.length;i++){var ai=analysis.items[i];if(!ai.selected)continue;await addDoc(collection(db,"tasks"),{title:ai.task,assignedTo:ai.name,deadline:ai.deadline||"",priority:ai.priority,status:"TODO",clubId:cid,description:"From meeting analysis",createdBy:user.uid,createdAt:new Date().toISOString()})}for(var j=0;j<analysis.risks.length;j++){var r=analysis.risks[j];await addDoc(collection(db,"risks"),{title:r.title,description:r.description,severity:r.severity,status:"OPEN",clubId:cid,createdAt:new Date().toISOString(),recommendation:"Review and address"})}sa(null);alert("Tasks and risks created!");if(cid)loadM(cid)}catch(e){alert("Error: "+e.message)}}
var hl=async function(){await signOut(auth);window.location.href="/login"};var hc=function(id){scid(id);sclub(clubs.find(function(x){return x.id===id}));loadM(id)};
function analyze(){if(!f.transcript.trim())return;saz(true);setTimeout(function(){sa(analyzeText(f.transcript));saz(false)},800)}

if(!user)return React.createElement("div",{className:"min-h-screen flex items-center justify-center"},React.createElement("div",{className:"skeleton w-8 h-8 rounded-full"}));
return React.createElement("div",{className:"flex min-h-screen"},React.createElement(Sidebar,{clubs:clubs,currentClubId:cid||"",userDisplayName:user?.email?.split("@")[0],clubRole:rn,onClubChange:hc,onLogout:hl,clubName:club?.name}),
React.createElement("main",{className:"flex-1 bg-gray-50 overflow-y-auto p-6"},React.createElement("div",{className:"max-w-6xl mx-auto"},
React.createElement("div",{className:"flex items-center justify-between mb-6"},React.createElement("h1",{className:"text-2xl font-bold"},"\ud83d\udcdd Meetings"),React.createElement("button",{className:"btn btn-primary",onClick:function(){return ssh(!sh)}},sh?"Cancel":"+ New Meeting")),
sh?React.createElement("div",{className:"card mb-6"},React.createElement("h3",{className:"font-semibold mb-4"},"New Meeting"),React.createElement("input",{className:"input mb-3",placeholder:"Meeting title",value:f.title,onChange:function(e){return sf({...f,title:e.target.value})}}),React.createElement("input",{className:"input mb-3",type:"date",value:f.date,onChange:function(e){return sf({...f,date:e.target.value})}}),React.createElement("textarea",{className:"textarea mb-3",placeholder:"Paste meeting notes or transcript...\nExample: Rahul will arrange the projector...",value:f.transcript,onChange:function(e){return sf({...f,transcript:e.target.value})},rows:5}),React.createElement("button",{className:"btn btn-primary",onClick:cr},"Create Meeting"),React.createElement("button",{className:"btn btn-sm ml-2",onClick:analyze,disabled:analyzing||!f.transcript.trim()},analyzing?"Analyzing...":"\u2728 Analyze Transcript")):null,
analysis?React.createElement("div",{className:"card mb-6 border-t-4 border-t-indigo-500"},React.createElement("h3",{className:"font-semibold mb-3"},"\u2728 AI Analysis Results"),React.createElement("div",{className:"grid grid-cols-2 gap-4 mb-3"},React.createElement("div",{className:"bg-indigo-50 rounded-lg p-3 text-center"},React.createElement("p",{className:"text-2xl font-bold text-indigo-600"},analysis.items.length),React.createElement("p",{className:"text-xs text-gray-500"},"Action Items")),React.createElement("div",{className:"bg-red-50 rounded-lg p-3 text-center"},React.createElement("p",{className:"text-2xl font-bold text-red-600"},analysis.risks.length),React.createElement("p",{className:"text-xs text-gray-500"},"Risks"))),analysis.items.length>0?React.createElement("div",{className:"space-y-2 mb-3"},analysis.items.map(function(ai,i){return React.createElement("label",{key:i,className:"flex items-center gap-3 p-2 bg-gray-50 rounded-lg cursor-pointer"},React.createElement("input",{type:"checkbox",checked:ai.selected,onChange:function(){var arr=[...analysis.items];arr[i]={...arr[i],selected:!arr[i].selected};sa({...analysis,items:arr})}}),React.createElement("div",{className:"flex-1 min-w-0"},React.createElement("p",{className:"text-sm font-medium"},ai.task),React.createElement("p",{className:"text-xs text-gray-500"},ai.name+(ai.deadline?" - "+ai.deadline:"")),React.createElement("span",{className:"badge "+(ai.priority==="CRITICAL"?"badge-red":ai.priority==="HIGH"?"badge-yellow":"badge-blue")},ai.priority)))})):null,analysis.risks.length>0?React.createElement("div",{className:"space-y-2 mb-3"},React.createElement("p",{className:"text-sm font-semibold text-red-600"},"Risks"),analysis.risks.map(function(r,i){return React.createElement("div",{key:i,className:"text-sm p-2 bg-red-50 rounded"},"\u26a0\ufe0f "+r.title+": "+r.description)})):null,React.createElement("button",{className:"btn btn-primary",onClick:approveItems},"Approve Selected ("+analysis.items.filter(function(x){return x.selected}).length+")"),React.createElement("button",{className:"btn ml-2",onClick:function(){sa(null)}},"Reject")):null,
meetings.length===0?React.createElement("div",{className:"empty-state"},React.createElement("div",{className:"empty-state-icon"},"\ud83d\udcdd"),React.createElement("p",{className:"empty-state-title"},"No meetings yet"),React.createElement("p",{className:"empty-state-text"},"Create a meeting with a transcript to use AI analysis")):React.createElement("div",{className:"space-y-3"},meetings.map(function(m){return React.createElement("div",{key:m.id,className:"card"},React.createElement("div",{className:"flex items-center justify-between"},React.createElement("h3",{className:"font-semibold"},m.title),m.aiProcessed?React.createElement("span",{className:"badge badge-green"},"\u2728 AI"):null),React.createElement("p",{className:"text-sm text-gray-500"},m.date?new Date(m.date).toLocaleDateString():""),m.transcript?React.createElement("p",{className:"text-sm text-gray-600 mt-2 line-clamp-2 whitespace-pre-wrap"},m.transcript.slice(0,200)):null)})))))
}
