'use client';
import{useState,useEffect}from'react';
import{initializeApp,getApps}from'firebase/app';
import{getAuth,signOut,onAuthStateChanged}from'firebase/auth';
import{getFirestore,collection,doc,getDoc,getDocs,query,where,addDoc,updateDoc,deleteDoc}from'firebase/firestore';
import Sidebar from'@/components/Sidebar';
const cfg={apiKey:"AIzaSyAAORXxX6tBpfCAtkEvWD_ls_VDhZuMdro",authDomain:"code-vidya-hack-day-ps-3-6b47d.firebaseapp.com",projectId:"code-vidya-hack-day-ps-3-6b47d"};
const app=getApps().length?getApps()[0]:initializeApp(cfg);const auth=getAuth(app);const db=getFirestore(app);

export default function SettingsPage(){
const[user,su]=useState(null);const[ck,sc]=useState(false);const[clubs,scl]=useState([]);const[cid,scid]=useState(null);const[club,sclub]=useState(null);const[tab,st]=useState('roles');
const[members,sm]=useState([]);const[roles,sr]=useState([]);const[rn,srn]=useState('');
useEffect(()=>{const un=onAuthStateChanged(auth,u=>{if(!u){window.location.href='/login';return;}su(u);sc(true);});return()=>un();},[]);
useEffect(()=>{if(ck)L();},[ck]);
async function L(){const q=query(collection(db,'clubMembers'),where('userId','==',user.uid),where('status','==','ACTIVE'));const sn=await getDocs(q);const mc=(await Promise.all(sn.docs.map(async d=>{const m=d.data()as any;const c=await getDoc(doc(db,'clubs',m.clubId));if(!c.exists())return null;return{id:c.id,...c.data(),membershipRole:m.role};}))).filter(Boolean);scl(mc);if(mc.length>0){scid(mc[0].id);sclub(mc[0]);const ms=await getDocs(query(collection(db,'clubMembers'),where('clubId','==',mc[0].id),where('status','==','ACTIVE')));sm(ms.docs.map(d=>({id:d.id,...d.data()})));const rs=await getDocs(query(collection(db,'roles'),where('clubId','==',mc[0].id)));sr(rs.docs.map(d=>({id:d.id,...d.data()})));if(mc[0].membershipRole==='OWNER')srn('Owner');}}
const hl=async()=>{await signOut(auth);window.location.href='/login';};const hc=async(id)=>{scid(id);sclub(clubs.find(x=>x.id===id));};
return(<div className="flex min-h-screen"><Sidebar clubs={clubs} currentClubId={cid||''} userDisplayName={user?.email?.split('@')[0]} clubRole={rn} onClubChange={hc} onLogout={hl} clubName={club?.name}/><main className="flex-1 bg-gray-50 overflow-y-auto p-6"><div className="max-w-5xl mx-auto"><h1 className="text-2xl font-bold mb-6">Settings</h1><div className="tabs mb-6"><button className={"tab"+(tab==='roles'?' active':'')} onClick={()=>st('roles')}>Roles & Permissions</button><button className={"tab"+(tab==='members'?' active':'')} onClick={()=>st('members')}>Members</button></div>{tab==='roles'&&<div><p className="text-sm text-gray-500 mb-4">Manage roles and permissions</p><div className="card mb-4"><div className="p-3 bg-gray-50 rounded-lg mb-2"><p className="font-semibold">👑 Owner</p><p className="text-sm text-gray-500">Full access</p></div><div className="p-3 bg-gray-50 rounded-lg"><p className="font-semibold">🛡️ Admin</p><p className="text-sm text-gray-500">Club management</p></div></div>{roles.map(r=><div key={r.id} className="card mb-2 flex justify-between"><div><p className="font-semibold">{r.name}</p><p className="text-sm text-gray-500">{r.description}</p></div></div>)}</div>}{tab==='members'&&<div className="space-y-2">{members.map(m=><div key={m.id} className="card flex justify-between"><div><p className="font-medium">{m.displayName||m.email||'User'}</p><p className="text-sm text-gray-500">{m.role||'Member'}</p></div></div>)}</div>}</div></main></div>);}