// ============ PERMISSION DEFINITIONS ============

export type Permission = 
  | 'VIEW_CLUB' | 'EDIT_CLUB'
  | 'VIEW_MEMBERS' | 'INVITE_MEMBERS' | 'REMOVE_MEMBERS' | 'MANAGE_MEMBER_ROLES' | 'MANAGE_MEMBER_PERMISSIONS'
  | 'VIEW_EVENTS' | 'CREATE_EVENTS' | 'EDIT_EVENTS' | 'DELETE_EVENTS' | 'MANAGE_EVENTS'
  | 'VIEW_TASKS' | 'CREATE_TASKS' | 'EDIT_TASKS' | 'DELETE_TASKS' | 'ASSIGN_TASKS' | 'MANAGE_TASKS'
  | 'VIEW_VOLUNTEERS' | 'MANAGE_VOLUNTEERS' | 'ASSIGN_VOLUNTEERS'
  | 'VIEW_MEETINGS' | 'CREATE_MEETINGS' | 'EDIT_MEETINGS' | 'DELETE_MEETINGS' | 'MANAGE_MEETINGS'
  | 'VIEW_DOCUMENTS' | 'UPLOAD_DOCUMENTS' | 'DELETE_DOCUMENTS' | 'MANAGE_DOCUMENTS'
  | 'VIEW_RISKS' | 'CREATE_RISKS' | 'MANAGE_RISKS' | 'RESOLVE_RISKS'
  | 'VIEW_ANNOUNCEMENTS' | 'CREATE_ANNOUNCEMENTS' | 'EDIT_ANNOUNCEMENTS' | 'PUBLISH_ANNOUNCEMENTS' | 'DELETE_ANNOUNCEMENTS'
  | 'USE_AI' | 'ANALYZE_MEETINGS' | 'USE_AI_ACTIONS' | 'RUN_RISK_ANALYSIS' | 'MANAGE_KNOWLEDGE_BASE'
  | 'VIEW_ANALYTICS'
  | 'MANAGE_CLUB_SETTINGS' | 'MANAGE_ROLES' | 'TRANSFER_OWNERSHIP';

export const ALL_PERMISSIONS: Permission[] = [
  'VIEW_CLUB', 'EDIT_CLUB',
  'VIEW_MEMBERS', 'INVITE_MEMBERS', 'REMOVE_MEMBERS', 'MANAGE_MEMBER_ROLES', 'MANAGE_MEMBER_PERMISSIONS',
  'VIEW_EVENTS', 'CREATE_EVENTS', 'EDIT_EVENTS', 'DELETE_EVENTS', 'MANAGE_EVENTS',
  'VIEW_TASKS', 'CREATE_TASKS', 'EDIT_TASKS', 'DELETE_TASKS', 'ASSIGN_TASKS', 'MANAGE_TASKS',
  'VIEW_VOLUNTEERS', 'MANAGE_VOLUNTEERS', 'ASSIGN_VOLUNTEERS',
  'VIEW_MEETINGS', 'CREATE_MEETINGS', 'EDIT_MEETINGS', 'DELETE_MEETINGS', 'MANAGE_MEETINGS',
  'VIEW_DOCUMENTS', 'UPLOAD_DOCUMENTS', 'DELETE_DOCUMENTS', 'MANAGE_DOCUMENTS',
  'VIEW_RISKS', 'CREATE_RISKS', 'MANAGE_RISKS', 'RESOLVE_RISKS',
  'VIEW_ANNOUNCEMENTS', 'CREATE_ANNOUNCEMENTS', 'EDIT_ANNOUNCEMENTS', 'PUBLISH_ANNOUNCEMENTS', 'DELETE_ANNOUNCEMENTS',
  'USE_AI', 'ANALYZE_MEETINGS', 'USE_AI_ACTIONS', 'RUN_RISK_ANALYSIS', 'MANAGE_KNOWLEDGE_BASE',
  'VIEW_ANALYTICS', 'MANAGE_CLUB_SETTINGS', 'MANAGE_ROLES', 'TRANSFER_OWNERSHIP',
];

export const PERMISSION_LABELS: Record<Permission, string> = {
  VIEW_CLUB: 'View Club', EDIT_CLUB: 'Edit Club',
  VIEW_MEMBERS: 'View Members', INVITE_MEMBERS: 'Invite Members', REMOVE_MEMBERS: 'Remove Members',
  MANAGE_MEMBER_ROLES: 'Manage Roles', MANAGE_MEMBER_PERMISSIONS: 'Manage Permissions',
  VIEW_EVENTS: 'View Events', CREATE_EVENTS: 'Create Events', EDIT_EVENTS: 'Edit Events',
  DELETE_EVENTS: 'Delete Events', MANAGE_EVENTS: 'Manage Events',
  VIEW_TASKS: 'View Tasks', CREATE_TASKS: 'Create Tasks', EDIT_TASKS: 'Edit Tasks',
  DELETE_TASKS: 'Delete Tasks', ASSIGN_TASKS: 'Assign Tasks', MANAGE_TASKS: 'Manage Tasks',
  VIEW_VOLUNTEERS: 'View Volunteers', MANAGE_VOLUNTEERS: 'Manage Volunteers', ASSIGN_VOLUNTEERS: 'Assign Volunteers',
  VIEW_MEETINGS: 'View Meetings', CREATE_MEETINGS: 'Create Meetings', EDIT_MEETINGS: 'Edit Meetings',
  DELETE_MEETINGS: 'Delete Meetings', MANAGE_MEETINGS: 'Manage Meetings',
  VIEW_DOCUMENTS: 'View Documents', UPLOAD_DOCUMENTS: 'Upload Documents', DELETE_DOCUMENTS: 'Delete Documents',
  MANAGE_DOCUMENTS: 'Manage Documents',
  VIEW_RISKS: 'View Risks', CREATE_RISKS: 'Create Risks', MANAGE_RISKS: 'Manage Risks', RESOLVE_RISKS: 'Resolve Risks',
  VIEW_ANNOUNCEMENTS: 'View Announcements', CREATE_ANNOUNCEMENTS: 'Create Announcements',
  EDIT_ANNOUNCEMENTS: 'Edit Announcements', PUBLISH_ANNOUNCEMENTS: 'Publish Announcements',
  DELETE_ANNOUNCEMENTS: 'Delete Announcements',
  USE_AI: 'Use AI', ANALYZE_MEETINGS: 'Analyze Meetings', USE_AI_ACTIONS: 'Use AI Actions',
  RUN_RISK_ANALYSIS: 'Run Risk Analysis', MANAGE_KNOWLEDGE_BASE: 'Manage Knowledge Base',
  VIEW_ANALYTICS: 'View Analytics',
  MANAGE_CLUB_SETTINGS: 'Manage Club Settings', MANAGE_ROLES: 'Manage Roles', TRANSFER_OWNERSHIP: 'Transfer Ownership',
};